name: ssilentscreams
description: "the fastest delivery in village"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  google_fonts: ^6.3.2
  expandable_page_view: ^1.0.17
  flutter_svg: ^2.2.2
  shared_preferences: ^2.5.3
  pinput: ^6.0.0

dev_dependencies:
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: assets/logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"

    image: assets/logo.png
    image_dark: assets/logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/load1.png
    - assets/images/success.png
    - assets/mapa.png
    - assets/images/splash/
    - assets/images/
    - assets/profile.png
    - assets/icons/

#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
